"use client";
import {useRef,useState} from "react";
import {Home,WandSparkles,Sparkles,User,Upload,Play,Pause,Download,Plus,Search,Heart,AudioLines} from "lucide-react";
type Post={id:number;title:string;author:string;tag:string};
const posts:Post[]=[{id:1,title:"MIDNIGHT DRIVE",author:"@RedzikFN",tag:"#night"},{id:2,title:"SLOWED VIBES",author:"@editmaster",tag:"#slowed"},{id:3,title:"PHONK RUN",author:"@KubaEdit",tag:"#phonk"}];
const presets=["SLOWED + REVERB","SPEED UP","NIGHTCORE","BASS BOOST","DREAMY","RADIO","PHONK","8D"];
export default function Page(){
 const [tab,setTab]=useState("home"),[file,setFile]=useState<File|null>(null),[url,setUrl]=useState(""),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState(1),[volume,setVolume]=useState(1),[query,setQuery]=useState("");
 const audio=useRef<HTMLAudioElement>(null),input=useRef<HTMLInputElement>(null);
 const choose=(f:File)=>{if(!f.type.startsWith("audio/"))return;setFile(f);setUrl(URL.createObjectURL(f));setTab("studio")};
 const toggle=()=>{if(!audio.current)return;audio.current.paused?(audio.current.play(),setPlaying(true)):(audio.current.pause(),setPlaying(false))};
 const download=()=>{if(!url)return;const a=document.createElement("a");a.href=url;a.download=file?.name||"edit.mp3";a.click()};
 const shown=posts.filter(p=>(p.title+p.author+p.tag).toLowerCase().includes(query.toLowerCase()));
 return <main><header><button className="logo" onClick={()=>setTab("home")}>♪ EDIT MUSIC</button><nav>{[["home",<Home/>,"Home"],["studio",<WandSparkles/>,"Studio"],["edittok",<Sparkles/>,"EditTok"],["profile",<User/>,"Profil"]].map(([id,icon,label])=><button className={tab===id?"nav active":"nav"} onClick={()=>setTab(String(id))} key={String(id)}>{icon}{label}</button>)}</nav><button className="upload" onClick={()=>input.current?.click()}><Upload/> Dodaj utwór</button><input hidden ref={input} type="file" accept="audio/*" onChange={e=>e.target.files?.[0]&&choose(e.target.files[0])}/></header>
 {tab==="home"&&<section className="page"><div className="hero"><div><small>⚡ NOWA ERA EDYCJI MUZYKI</small><h1>YOUR SOUND.<br/><em>YOUR EDIT.</em></h1><p>Edytuj muzykę, twórz własne wersje i publikuj je w EditTok.</p><button className="cta" onClick={()=>input.current?.click()}><Plus/> Zacznij edycję</button></div><AudioLines size={180}/></div><h2>Popularne edity</h2><div className="grid">{shown.map(p=><Card key={p.id} p={p}/>)}</div></section>}
 {tab==="studio"&&<section className="page"><h2>Studio</h2>{!file?<div className="drop" onClick={()=>input.current?.click()}><Upload size={45}/><h3>Wrzuć utwór tutaj</h3><p>MP3, WAV, OGG, M4A</p></div>:<><audio ref={audio} src={url}/><div className="player"><button className="play" onClick={toggle}>{playing?<Pause/>:<Play/>}</button><b>{file.name}</b><button className="ghost" onClick={download}><Download/> Oryginał</button></div><div className="presets"><b>Presety</b>{presets.map(x=><button key={x} onClick={()=>x==="SPEED UP"?setSpeed(1.3):x==="SLOWED + REVERB"&&setSpeed(.78)}>{x}</button>)}</div><div className="editor"><Control n="Głośność" v={volume} min={0} max={1.5} set={setVolume}/><Control n="Speed" v={speed} min={.5} max={2} set={setSpeed}/>{["Bass","Treble","Reverb","Echo / Delay","Pitch","Stereo Width"].map(n=><Control key={n} n={n} v={0} min={-1} max={1} set={()=>{}}/>)}</div><button className="cta publish" onClick={()=>setTab("edittok")}><Sparkles/> Publikuj w EditTok</button></>}</section>}
 {tab==="edittok"&&<section className="page"><div className="feedtop"><div><h2>EditTok</h2><p>TikTok, ale dla editów 🎧</p></div><div className="search"><Search/><input placeholder="Szukaj..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="chips">{["Dla Ciebie","Trending","Nowe","Slowed","Speed Up","Phonk","8D"].map(x=><button key={x}>{x}</button>)}</div><div className="feed">{shown.map(p=><Card key={p.id} p={p} big/>)}</div></section>}
 {tab==="profile"&&<section className="page"><div className="profile"><div className="avatar">R</div><div><h2>RedzikFN</h2><p>@RedzikFN</p><b>3 Editów</b></div></div><h2>Twoje edity</h2><div className="grid">{posts.filter(p=>p.author==="@RedzikFN").map(p=><Card key={p.id} p={p}/>)}</div></section>}
 </main>
}
function Control({n,v,min,max,set}:{n:string;v:number;min:number;max:number;set:(x:number)=>void}){return <label className="control"><span>{n}<b>{v.toFixed(2)}</b></span><input type="range" min={min} max={max} step=".01" value={v} onChange={e=>set(+e.target.value)}/></label>}
function Card({p,big=false}:{p:Post;big?:boolean}){const [on,setOn]=useState(false);return <article className={big?"card big":"card"}><div className="cover"><AudioLines size={70}/></div><div className="body"><span>{p.tag}</span><h3>{p.title}</h3><p>{p.author}</p><button className="round" onClick={()=>setOn(!on)}>{on?<Pause/>:<Play/>}</button><small><Heart/> 0 · 0 odtw.</small></div></article>}